# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1538a7b0a4d96f2c0b642ffe51058994"
name = "My First Custom App HOL"
handle = "my-first-custom-app-hol"
application_url = "https://pentium-beth-agenda-designers.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-6fcb2336.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pentium-beth-agenda-designers.trycloudflare.com/auth/callback",
  "https://pentium-beth-agenda-designers.trycloudflare.com/auth/shopify/callback",
  "https://pentium-beth-agenda-designers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
